<?php
/**
 * @version    $Id$
 * @package    IG_Plugin_Framework
 * @author     InnoThemes Team <support@innothemes.com>
 * @copyright  Copyright (C) 2012 InnoThemes.com. All Rights Reserved.
 * @license    GNU/GPL v2 or later http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Websites: http://www.innothemes.com
 * Technical Support:  Feedback - http://www.innothemes.com/contact-us/get-support.html
 */

class IG_Gadget_Contactform_Js_Visualdesign_Controls extends IG_Gadget_Base {

	/**
	 * Gadget file name without extension.
	 *
	 * @var  string
	 */
	protected $gadget = 'contactform-js-visualdesign-controls';

	/**
	 * Constructor.
	 *
	 * @return  void
	 */
	public function __construct() {

	}

	/**
	 *  set default action
	 */
	public function default_action() {
		require_once(ABSPATH . 'wp-admin/includes/admin.php');
		auth_redirect();

		header( 'Content-Type: application/javascript' );
		$controls = array();
		$controls[ 'single-line-text' ] = 'JSNVisualDesign.register("single-line-text", {caption:"Single-line Input", group:"standard", defaults:{label:"Single-line Input", instruction:"", required:0, limitation:0, limitMin:0, limitMax:0, limitType:"Words", size:"jsn-input-medium-fluid", value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><size/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, size:{type:"select", label:"Size", options:{"jsn-input-mini-fluid":"Mini", "jsn-input-small-fluid":"Small", "jsn-input-medium-fluid":"Medium", "jsn-input-xlarge-fluid":"Large"}, attrs:{"class":"input-medium"}}}}}, values:{value:{type:"text", label:"Predefined Value"}, limit:{type:"group", decorator:\'<div class="jsn-form-bar"><limitation/><limitMin/><limitMax/><limitType/></div>\', elements:{limitation:{type:"checkbox", label:"Limit text"}, limitMin:{type:"number", label:"within", validate:["number"]}, limitMax:{type:"number", label:"and", validate:["number"]}, limitType:{type:"select", options:{Words:"Words", Characters:"Characters"}, attrs:{"class":"input-small"}}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><input type="text" placeholder="${value}" class="${size}"/></div></div>\'});';
		$controls[ 'choices' ] = 'JSNVisualDesign.register("choices", {caption:"Radio Buttons", group:"standard", defaults:{label:"Radio Buttons", instruction:"", required:0, randomize:0, labelOthers:"Others", layout:"columns-count-one", items:[{text:"Choice 1", checked:true}, {text:"Choice 2", checked:false}, {text:"Choice 3", checked:false}], value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><layout/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, layout:{type:"select", label:"Layout", options:{"jsn-columns-count-one":"One Column", "jsn-columns-count-two":"Two Columns", "jsn-columns-count-three":"Three Columns", "jsn-columns-count-no":"Side by Side"}, attrs:{"class":"input-medium"}}}}}, values:{items:{type:"itemlist", label:"Items", actionField:true, multipleCheck:false}, itemAction:{type:"hidden"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><div class="control-group {{if hideField}}ig-hidden-field{{/if}}"><div class="controls ig-allow-other"><allowOther/><labelOthers/></div></div></div><div class="pull-right"><randomize/></div><div class="clearbreak"></div></div>\', elements:{allowOther:{type:"checkbox", field:"allowOther", label:t["IG_CONTACTFORM_ALLOW_USER_CHOICE"]}, labelOthers:{type:"_text", field:"allowOther", attrs:{"class":"text jsn-input-small-fluid"}}, randomize:{type:"checkbox", label:"Randomize Items"}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><div class="jsn-columns-container ${layout}">{{each(i, val) items}}<div class="jsn-column-item"><label class="radio"><input name="${identify}" type="radio" {{if val.checked == true || val.checked=="true"}}checked{{/if}} />${val.text}</label></div>{{/each}}{{if allowOther}}<div class="jsn-column-item"><label class="radio lbl-allowOther"><input class="allowOther" value="Others" type="radio" />${labelOthers}</label><textarea rows="3"></textarea></div>{{/if}}<div class="clearbreak"></div></div></div></div>\'});';
		$controls[ 'dropdown' ] = ' JSNVisualDesign.register("dropdown", {caption:"Dropdown", group:"standard", defaults:{label:"Dropdown", instruction:"", required:0, labelOthers:"Others", size:"jsn-input-fluid", items:[{text:"- Select Value -", checked:true},{text:"Value 1", checked:false},{text:"Value 2", checked:false}, {text:"Value 3", checked:false}], value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, inputsize:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><size/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, size:{type:"select", label:"Size", options:{"jsn-input-fluid":"Auto", "jsn-input-mini-fluid":"Mini", "jsn-input-small-fluid":"Small", "jsn-input-medium-fluid":"Medium", "jsn-input-xlarge-fluid":"Large"}, attrs:{"class":"input-medium"}}}}}, values:{items:{type:"itemlist", label:"Items", actionField:true, multipleCheck:false}, itemAction:{type:"hidden"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><div class="control-group {{if hideField}}ig-hidden-field{{/if}}"><div class="controls ig-allow-other"><allowOther/><labelOthers/></div></div></div><div class="pull-right"><randomize/></div><div class="clearbreak"></div></div><div class="jsn-form-bar"><div class="pull-left"><firstItemAsPlaceholder/></div><div class="clearbreak"></div></div>\', elements:{allowOther:{type:"checkbox", field:"allowOther", label:t["IG_CONTACTFORM_ALLOW_USER_CHOICE"]}, labelOthers:{type:"_text", field:"allowOther", attrs:{"class":"text jsn-input-small-fluid"}}, randomize:{type:"checkbox", label:"Randomize Items"}, firstItemAsPlaceholder:{type:"checkbox", label:t["IG_CONTACTFORM_SET_ITEM_PLACEHOLDER"]}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><select class="${size}" >{{each(i, val) items}}<option value="${val.text}" {{if val.checked == true || val.checked=="true"}}selected{{/if}}>${val.text}</option>{{/each}}</select></div></div>\'});';
		$controls[ 'paragraph-text' ] = '  JSNVisualDesign.register("paragraph-text", {caption:"Multi-line Input", group:"standard", defaults:{label:"Multi-line Input", instruction:"", required:0, limitation:0, limitMin:0, limitMax:0, rows:8, size:"jsn-input-xlarge-fluid", limitType:"Words", value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><rows/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, rows:{type:"number", label:"Rows", validate:["number"]}}}}, values:{value:{type:"textarea", label:"Predefined Value", attrs:{rows:"10"}}, limit:{type:"group", decorator:\'<div class="jsn-form-bar"><limitation/><limitMin/><limitMax/><limitType/></div>\', elements:{limitation:{type:"checkbox", label:"Limit text"}, limitMin:{type:"number", label:"within", validate:["number"]}, limitMax:{type:"number", label:"and", validate:["number"]}, limitType:{type:"select", options:{Words:"Words", Characters:"Characters"}, attrs:{"class":"input-small"}}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><textarea class="${size}" rows="${rows}" placeholder="${value}"></textarea></div></div>\'});';
		$controls[ 'checkboxes' ] = ' JSNVisualDesign.register("checkboxes", {caption:"Checkboxes", group:"standard", defaults:{label:"Checkboxes", instruction:"", required:0, randomize:0, allowOther:0, layout:"columns-count-one", labelOthers:"Others", items:[{text:"Checkbox 1", checked:false}, {text:"Checkbox 2", checked:false}, {text:"Checkbox 3", checked:false}], value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><layout/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, layout:{type:"select", label:"Layout", options:{"jsn-columns-count-one":"One Column", "jsn-columns-count-two":"Two Columns", "jsn-columns-count-three":"Three Columns", "jsn-columns-count-no":"Side by Side"}, attrs:{"class":"input-medium"}}}}}, values:{items:{type:"itemlist", label:"Items", actionField:true, multipleCheck:true}, itemAction:{type:"hidden"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><div class="control-group {{if hideField}}ig-hidden-field{{/if}}"><div class="controls ig-allow-other"><allowOther/><labelOthers/></div></div></div><div class="pull-right"><randomize/></div><div class="clearbreak"></div></div>\', elements:{allowOther:{type:"checkbox", field:"allowOther", label:t["IG_CONTACTFORM_ALLOW_USER_CHOICE"]}, labelOthers:{type:"_text", field:"allowOther", attrs:{"class":"text jsn-input-small-fluid"}}, randomize:{type:"checkbox", label:"Randomize Items"}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><div class="jsn-columns-container ${layout}">{{each(i, val) items}}<div class="jsn-column-item"><label class="checkbox"><input type="checkbox" {{if val.checked == true || val.checked == "true"}}checked{{/if}} />${val.text}</label></div>{{/each}}{{if allowOther==true || allowOther=="true"}}<div class="jsn-column-item"><label class="checkbox lbl-allowOther"><input class="allowOther" value="Others" type="checkbox" />${labelOthers}</label><textarea rows="3"></textarea></div>{{/if}}<div class="clearbreak"></div></div></div></div>\'});';
		$controls[ 'list' ] = ' JSNVisualDesign.register("list", {caption:"List", group:"standard", defaults:{label:"List", instruction:"", required:0, size:"jsn-input-fluid", items:[{text:"Value 1", checked:false}, {text:"Value 2", checked:false}, {text:"Value 3", checked:false}], value:""}, params:{general:{label:{type:"text", label:"Title"}, customClass:{type:"text", label:"Class"}, instruction:{type:"textarea", label:"Instruction"}, inputsize:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><required/><hideField/></div><div class="pull-right"><size/></div><div class="clearbreak"></div></div>\', elements:{required:{type:"checkbox", label:"Required"}, hideField:{type:"checkbox", label:"Hidden"}, size:{type:"select", label:"Size", options:{"jsn-input-fluid":"Auto", "jsn-input-mini-fluid":"Mini", "jsn-input-small-fluid":"Small", "jsn-input-medium-fluid":"Medium", "jsn-input-xlarge-fluid":"Large"}, attrs:{"class":"input-medium"}}}}}, values:{items:{type:"itemlist", label:"Items", actionField:false, multipleCheck:true}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><multiple/></div><div class="pull-right"><randomize/></div><div class="clearbreak"></div></div>\', elements:{multiple:{type:"checkbox", label:"Allow multiple selection"}, randomize:{type:"checkbox", label:"Randomize Items"}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><label class="control-label">${label}{{if required==1||required=="1"}}<span class="required">*</span>{{/if}}{{if instruction}}<i class="icon-question-sign"></i>{{/if}}</label><div class="controls"><select multiple class="${size}" >{{each(i, val) items}}<option value="${val.text}" {{if val.checked == true || val.checked=="true"}}selected{{/if}}>${val.text}</option>{{/each}}</select></div></div>\'});';
		$controls[ 'static-content' ] = 'JSNVisualDesign.register("static-content", {caption:"Text", group:"standard", defaults:{label:"Text", value:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris fermentum odio sed ipsum fringilla ut tempor magna accumsan. Aliquam erat volutpat. Vestibulum euismod ipsum non risus dignissim hendrerit. Nam metus arcu, blandit in cursus nec, placerat vitae arcu. Maecenas ornare porta mi, et tincidunt nulla luctus non.”"}, params:{general:{value:{type:"textarea", label:"Text", attrs:{rows:"6"}}, customClass:{type:"text", label:"Class"}, extra:{type:"group", decorator:\'<div class="jsn-form-bar"><div class="pull-left"><hideField/></div><div class="clearbreak"></div></div>\', elements:{hideField:{type:"checkbox", label:"Hidden"}}}}}, tmpl:\'<div class="control-group ${customClass} {{if hideField}}ig-hidden-field{{/if}}"><div class="controls clearfix">{{html value}}</div></div>\'});';
		$controls[ 'form-captcha' ] = 'JSNVisualDesign.register("form-captcha", {caption:"Form Captcha", group:"extra", defaults:{}, params:{general:{formCaptcha:{type:"select", options:{0:"No Captcha", 1:"ReCaptcha", 2:"Securimage"}, label:"Captcha Integration"}}}, tmpl:"Form Captcha"});';
		$controls[ 'form-actions' ] = 'JSNVisualDesign.register("form-actions", {caption:"Form Action", group:"extra", defaults:{btnSubmit:"Submit", btnReset:"Reset", btnNext:"Next", btnPrev:"Prev"}, params:{general:{btnSubmit:{type:"text", label:"Submit Button Text"}, stateBtnReset:{type:"radio", options:{No:"No", Yes:"Yes"}, "class":"radio inline", label:"Show Button Reset"}, btnReset:{type:"text", label:"Reset Button Text", attrs:{"class":"hide"}}, btnNext:{type:"text", label:"Next Button Text"}, btnPrev:{type:"text", label:"Prev Button Text"}}}, tmpl:"Form Action"});';
		$controls = apply_filters( 'ig_contactform_filter_visualdesign_controls', $controls );
		$javascript = '(function ($) {
			    var t = $.evalJSON($("#ig_contactform_languages").val());
			    ' . implode( ' ', $controls ) . '
			})(jQuery);';
		echo '' . $javascript;
		exit();
	}


}
